In [52]:
import numpy as np
import pandas as pd

# Creating a DataFrame

In [53]:
data={
      'Name':['john','anna','pater','linda'],
      'Age' :[45,56,23,43],
      'City':['jatni','bbsr','burla','banglore'],
      'salary':[50000,60000,35000,100000]
}
df=pd.DataFrame(data)

In [54]:
df

    Name  Age      City  salary
0   john   45     jatni   50000
1   anna   56      bbsr   60000
2  pater   23     burla   35000
3  linda   43  banglore  100000

In [55]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
data2=data_list
df2=pd.DataFrame(data2)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [56]:
col=['Name','Age','City','Salary']
df2=pd.DataFrame(data2,columns=col)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**accesing a data frame is not by indexing but by colums**

In [57]:
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [58]:
df2[["Name","Age"]]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

**Creating a Column**

In [59]:
df2["Designation"]=["Engg.","Doc.","Engg.","Doc."]

In [60]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000       Engg.
1   Anna   34     Paris   70000        Doc.
2  Peter   29    Berlin   62000       Engg.
3  Linda   42    London   85000        Doc.

**Drop a Column**

 **implace=True use karne se actual data me changes hoga otherwise temporary change only**

In [61]:
df2.drop(["Designation","City"],axis=1)

    Name  Age  Salary
0   John   28   65000
1   Anna   34   70000
2  Peter   29   62000
3  Linda   42   85000

In [62]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000       Engg.
1   Anna   34     Paris   70000        Doc.
2  Peter   29    Berlin   62000       Engg.
3  Linda   42    London   85000        Doc.

**Drop a Row**

In [63]:
df2.drop(0,axis=0)

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000        Doc.
2  Peter   29  Berlin   62000       Engg.
3  Linda   42  London   85000        Doc.

**accessing a row**

In [64]:
df2.loc[[0]]

   Name  Age      City  Salary Designation
0  John   28  New York   65000       Engg.

In [65]:
df2.loc[[0,1]]

   Name  Age      City  Salary Designation
0  John   28  New York   65000       Engg.
1  Anna   34     Paris   70000        Doc.

In [66]:
df.loc[3]

Name         linda
Age             43
City      banglore
salary      100000
Name: 3, dtype: object

In [67]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000       Engg.
1   Anna   34     Paris   70000        Doc.
2  Peter   29    Berlin   62000       Engg.
3  Linda   42    London   85000        Doc.

# Subset of Rows & Columns

**1st block selects the row & 2nd blok selects the column**

In [68]:
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

#  Conditional Selection

In [69]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000       Engg.
1   Anna   34     Paris   70000        Doc.
2  Peter   29    Berlin   62000       Engg.
3  Linda   42    London   85000        Doc.

# I want only those ehose age is above 30

In [70]:
df[df["Age"]>30]

    Name  Age      City  salary
0   john   45     jatni   50000
1   anna   56      bbsr   60000
3  linda   43  banglore  100000

In [76]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000       Engg.
1   Anna   34     Paris   70000        Doc.
2  Peter   29    Berlin   62000       Engg.
3  Linda   42    London   85000        Doc.

# I only want poeple whose age is above 30 and their city must be New York

In [77]:
df2[(df2["Age"]<30) & (df2["City"]=='New York')]

   Name  Age      City  Salary Designation
0  John   28  New York   65000       Engg.